name: terraform-run
on: workflow_dispatch

jobs:
  terraform_run:   
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4  # Checkout the repo

      - name: Terraform Init
        run: terraform init
