name: terraform-run

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch

jobs:
  terraform_run:   
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4  # Checkout the repo

      - name: Terraform Init
        run: terraform init
